-- Generated by ChatGPT
-- Applications Table
CREATE TABLE Applications (
    ApplicationId INT PRIMARY KEY IDENTITY(1,1),
    ApplicationName NVARCHAR(255) UNIQUE NOT NULL,
    ApplicationUrl NVARCHAR(512),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE() ON UPDATE GETDATE()
);

-- Users Table
CREATE TABLE Users (
    UserId INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(255) UNIQUE NOT NULL,
    Email NVARCHAR(255) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(512) NOT NULL,
    FirstName NVARCHAR(100),
    LastName NVARCHAR(100),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE() ON UPDATE GETDATE()
);

-- Sessions Table
CREATE TABLE Sessions (
    SessionId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId INT,
    ApplicationId INT,
    Token NVARCHAR(512) UNIQUE NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    ExpiresAt DATETIME,
    FOREIGN KEY (UserId) REFERENCES Users(UserId),
    FOREIGN KEY (ApplicationId) REFERENCES Applications(ApplicationId)
);

-- AuditLog Table
CREATE TABLE AuditLog (
    AuditId INT PRIMARY KEY IDENTITY(1,1),
    UserId INT,
    ApplicationId INT,
    RequestTime DATETIME DEFAULT GETDATE(),
    Action NVARCHAR(255),
    Status NVARCHAR(50),
    Details NVARCHAR(MAX),
    FOREIGN KEY (UserId) REFERENCES Users(UserId),
    FOREIGN KEY (ApplicationId) REFERENCES Applications(ApplicationId)
);
